version: '3'

services:
  flask-python-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5090:5090"
    environment:
      PORT: 5090
      DB_USER: "postgres"
      DB_PASSWORD: "veryCoolPassword"
      DB_NAME: "flask-finance-db"
      DB_HOST: "db"
  db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "veryCoolPassword"
      POSTGRES_DB: "flask-finance-db"
    ports:
      - "5432:5432"
